[mqtt]
host=localhost
port=1883

[rest]
; Base URL of the REST API (no trailing slash!)
baseUrl=http://localhost:7000
vesselFinderBaseUrl=http://localhost:8000
vesselFinderSimId=put-simulation-id-here

[signalr]
host=localhost
port=7007
apiKey=IRIDESS_CONTROL_ROOM
userId=control-room-user
